# /workspaces/WazeLog/routing/osrm_local/docker-compose.yml

services:
  osrm-backend:
    image: osrm/osrm-backend:latest
    container_name: osrm_backend_sp # Nome do container atualizado
    restart: unless-stopped
    ports:
      - "5000:5000" # Mapeia a porta 5000 do container para a porta 5000 do host
    volumes:
      - ./data:/data # Mapeia a pasta local 'data' para '/data' dentro do container
    # Comando atualizado para usar o arquivo .osrm de Sudeste
    command: osrm-routed --algorithm mld /data/sudeste-latest.osrm

  # Serviço temporário para processar os dados do mapa (executa apenas uma vez)
  osrm-preprocess:
    image: osrm/osrm-backend:latest
    container_name: osrm_preprocess_sp # Nome do container atualizado
    volumes:
      - ./data:/data
    # Sequência de comandos atualizada para processar o arquivo .osm.pbf de Sudeste
    # 1. Extrair a rede de estradas para carros
    # 2. Particionar a rede (necessário para o algoritmo MLD)
    # 3. Customizar os dados particionados
    # O resultado será o arquivo sudeste-latest.osrm e outros auxiliares na pasta ./data
    command: >
      bash -c "
      if [ ! -f /data/sudeste-latest.osm.pbf ]; then
          echo '--- ERRO: Arquivo /data/sudeste-latest.osm.pbf não encontrado. Faça o download do Geofabrik e coloque na pasta ./data ---'
          exit 1
      fi;
      echo '--- Iniciando pré-processamento OSRM para Sudeste ---' &&
      osrm-extract -p /opt/car.lua /data/sudeste-latest.osm.pbf &&
      echo '--- Extração concluída ---' &&
      osrm-partition /data/sudeste-latest.osrm &&
      echo '--- Particionamento concluído ---' &&
      osrm-customize /data/sudeste-latest.osrm &&
      echo '--- Customização concluída ---' &&
      echo '--- Pré-processamento OSRM concluído com sucesso! ---'
      "